#+STARTUP: indent
#+DRAWERS: PROPERTIES
#+TITLE: data_collector package for monitoring with SARAD instruments
#+AUTHOR:    Michael Strey
#+EMAIL:     strey@sarad.de
#+LANGUAGE: en
#+OPTIONS: toc:2 H:5 email:t tags:t |:t todo:t d:nil
- sari :: a class library to access SARAD instruments via their serial
          interfaces, comprises all recent SARAD instruments with their
          proprietary protocols
- radonscout :: a module for the adapter to the instruments of the Radon Scout family
- dacm :: a module for the adapter to the instruments of the DACM family
- doseman :: a module for the adapter to the instruments of the DOSEman family
             (uncomplete, since the DOSEman family is not suited for monitoring applications)
- data_collector :: a sample command line application to demonstrate the usage
                    of the package.  It allows to send measuring values to a
                    Zabbix server or publish MQTT messages or to display values.

* Caveat
Work in progress.
Code might be buggy, clumsy or uncomplete.
Be careful, feel free to improve things and come back to me with questions.

-- Michael Strey

* What is it about?
SARAD GmbH is a manufacturer of instruments for environmental measuring with a
focus on radioactivity, radon and gases. All instruments have a serial interface
-- usually a RS-232, RS-422 or USB creating a virtual serial port -- for remote
control, configuration, telemetry and data download. The protocol on the serial
interface is proprietary and differs from device family to device family and
even between device types. Up to now, the instruments can only be controlled
with the proprietary software applications provided by SARAD.

This package is an attempt to empower SARAD customers to make their own software
solutions to control SARAD instruments. It brings all proprietary SARAD
protocols and instruments together and allows to access them via a unique
software interface.

* Getting started
Requires Python 3.

Clone the repository to your local computer and move into the directory.
#+BEGIN_SRC shell
sudo pip install --editable ./
#+END_SRC

Afterwards you should be able to run the sample application by for instance calling
#+BEGIN_SRC shell
data_collector cluster
#+END_SRC

Get further help with
#+BEGIN_SRC shell
data_collector --help
#+END_SRC

*Read the code!*
